# Generated by Django 5.1.2 on 2024-11-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_gmatmodule_gremodule_ieltsmodule_satmodule_and_more'),
        ('exam_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='gmat_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.gmatquestion'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='gre_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.grequestion'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ielts_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.ieltsquestion'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='sat_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.satquestion'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name='ExamDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmat_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.gmatexam')),
                ('gre_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.greexam')),
                ('ielts_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.ieltsexam')),
                ('sat_exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.satexam')),
            ],
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_display.examdisplay'),
        ),
    ]
