# Generated by Django 5.1.2 on 2024-11-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='graph_image',
            field=models.ImageField(blank=True, null=True, upload_to='graph_images/'),
        ),
    ]
