# Generated by Django 5.1.2 on 2024-11-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
