# Generated by Django 5.1.2 on 2024-11-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_activity_options_alter_activity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmatexamsubmission',
            name='changes_made',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gmatquestion',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='grequestion',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='ieltsquestion',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='satquestion',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
