# Generated by Django 5.1.2 on 2024-11-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='test_type',
            field=models.CharField(blank=True, choices=[('gmat', 'GMAT'), ('gre', 'GRE'), ('sat', 'SAT'), ('ielts', 'IELTS')], max_length=50),
        ),
    ]
